export enum RolesEnum {
  ADMINISTRADOR = "ADMINISTRADOR",
  GERENTE_INVENTARIO = "GERENTE INVENTARIO",
  ENCARGADO_ALMACEN = "ENCARGADO ALMACEN",
  OPERADOR_TECNICO = "OPERADOR TECNICO",
  COMPRAS = "COMPRAS",
  AUDITOR = "AUDITOR",
}

export const rolesOptions: RolesEnum[] = [
  RolesEnum.ADMINISTRADOR,
  RolesEnum.GERENTE_INVENTARIO,
  RolesEnum.ENCARGADO_ALMACEN,
  RolesEnum.OPERADOR_TECNICO,
  RolesEnum.COMPRAS,
  RolesEnum.AUDITOR,
];
